# Generated by Django 5.1.15 on 2026-05-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="groupmemberprojection",
            new_name="media_group_group_i_f78165_idx",
            old_name="media_groupm_group_id_0c2d9e_idx",
        ),
        migrations.RenameIndex(
            model_name="groupmemberprojection",
            new_name="media_group_user_id_7daf79_idx",
            old_name="media_groupm_user_id_8af01e_idx",
        ),
    ]
