# Generated by Django 5.1.15 on 2026-06-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0003_outboxmessage_inboxmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="media_inbox_event_t_3a44fd_idx",
            old_name="media_inbox_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="media_inbox_routing_643432_idx",
            old_name="media_inbox_routing_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="media_outbo_status_3398ad_idx",
            old_name="media_outbox_status_available_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="media_outbo_routing_477645_idx",
            old_name="media_outbox_routing_idx",
        ),
    ]
