# Generated by Django 5.1.15 on 2026-06-25 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_files", "0005_email_art_name_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expense_id", models.UUIDField(unique=True)),
                ("group_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UPDATED", "Updated"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("payer_user_id", models.UUIDField(blank=True, null=True)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "media_expense_projections",
            },
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["group_id", "created_at"], name="media_files_group_i_31711a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["related_expense_id", "created_at"],
                name="media_files_related_514aee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["uploaded_by_user_id", "created_at"],
                name="media_files_uploade_d4f220_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expenseprojection",
            index=models.Index(
                fields=["group_id"], name="media_expen_group_i_c143c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenseprojection",
            index=models.Index(fields=["status"], name="media_expen_status_b07bb6_idx"),
        ),
    ]
