# Generated by ChatGPT - initial migration for expenses app
from django.db import migrations, models
import uuid
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserProjection',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('identity_user_id', models.UUIDField(unique=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=255, null=True, blank=True)),
                ('first_name', models.CharField(max_length=150, null=True, blank=True)),
                ('last_name', models.CharField(max_length=150, null=True, blank=True)),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'expenses_userprojection'},
        ),
        migrations.CreateModel(
            name='GroupProjection',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('group_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('created_by_user_id', models.UUIDField()),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'expenses_groupprojection'},
        ),
        migrations.CreateModel(
            name='GroupMemberProjection',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('group_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('display_name_snapshot', models.CharField(max_length=255, null=True, blank=True)),
                ('role', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('joined_at', models.DateTimeField(null=True, blank=True)),
                ('left_at', models.DateTimeField(null=True, blank=True)),
                ('removed_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'expenses_groupmemberprojection'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('group_id', models.UUIDField(db_index=True)),
                ('created_by_user_id', models.UUIDField()),
                ('payer_user_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True, blank=True)),
                ('currency', models.CharField(max_length=10, default='IRR')),
                ('base_amount_minor', models.BigIntegerField()),
                ('tax_type', models.CharField(max_length=20)),
                ('tax_percentage', models.DecimalField(max_digits=7, decimal_places=4, null=True, blank=True)),
                ('tax_amount_minor', models.BigIntegerField(default=0)),
                ('service_fee_type', models.CharField(max_length=20)),
                ('service_fee_percentage', models.DecimalField(max_digits=7, decimal_places=4, null=True, blank=True)),
                ('service_fee_amount_minor', models.BigIntegerField(default=0)),
                ('total_amount_minor', models.BigIntegerField()),
                ('split_method', models.CharField(max_length=20)),
                ('receipt_file_id', models.UUIDField(null=True, blank=True)),
                ('receipt_url', models.CharField(max_length=1024, null=True, blank=True)),
                ('status', models.CharField(max_length=10)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True, blank=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={'db_table': 'expenses_expense'},
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('display_name_snapshot', models.CharField(max_length=255, null=True, blank=True)),
                ('base_share_minor', models.BigIntegerField()),
                ('tax_share_minor', models.BigIntegerField(default=0)),
                ('service_fee_share_minor', models.BigIntegerField(default=0)),
                ('total_share_minor', models.BigIntegerField()),
                ('is_included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='participants', to='expenses.Expense')),
            ],
            options={'db_table': 'expenses_expenseparticipant'},
        ),
        migrations.AddIndex(
            model_name='groupmemberprojection',
            index=models.Index(fields=['group_id'], name='expenses_grou_group_id_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmemberprojection',
            index=models.Index(fields=['user_id'], name='expenses_grou_user_id_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseparticipant',
            unique_together={('expense', 'user_id')},
        ),
    ]
"""Initial migration for expenses app."""
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProjection",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("identity_user_id", models.UUIDField(unique=True)),
                ("phone_number", models.CharField(max_length=32)),
                ("display_name", models.CharField(max_length=255, null=True, blank=True)),
                ("first_name", models.CharField(max_length=255, null=True, blank=True)),
                ("last_name", models.CharField(max_length=255, null=True, blank=True)),
                ("role", models.CharField(max_length=32, default="USER")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "expenses_user_projections"},
        ),
        migrations.CreateModel(
            name="GroupProjection",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("group_id", models.UUIDField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("group_type", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32, default="ACTIVE")),
                ("created_by_user_id", models.UUIDField()),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "expenses_group_projections"},
        ),
        migrations.CreateModel(
            name="GroupMemberProjection",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("group_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("phone_number", models.CharField(max_length=32)),
                ("display_name_snapshot", models.CharField(max_length=255, null=True, blank=True)),
                ("role", models.CharField(max_length=16)),
                ("status", models.CharField(max_length=16, default="ACTIVE")),
                ("joined_at", models.DateTimeField(null=True, blank=True)),
                ("left_at", models.DateTimeField(null=True, blank=True)),
                ("removed_at", models.DateTimeField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "expenses_group_member_projections"},
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("group_id", models.UUIDField()),
                ("created_by_user_id", models.UUIDField()),
                ("payer_user_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True, blank=True)),
                ("currency", models.CharField(max_length=8, default="IRR")),
                ("base_amount_minor", models.BigIntegerField()),
                ("tax_type", models.CharField(max_length=32, default="NONE")),
                ("tax_percentage", models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)),
                ("tax_amount_minor", models.BigIntegerField(default=0)),
                ("service_fee_type", models.CharField(max_length=32, default="NONE")),
                ("service_fee_percentage", models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)),
                ("service_fee_amount_minor", models.BigIntegerField(default=0)),
                ("total_amount_minor", models.BigIntegerField()),
                ("split_method", models.CharField(max_length=32)),
                ("receipt_file_id", models.UUIDField(null=True, blank=True)),
                ("receipt_url", models.CharField(max_length=1024, null=True, blank=True)),
                ("status", models.CharField(max_length=16, default="ACTIVE")),
                ("expense_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True, blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={"db_table": "expenses"},
        ),
        migrations.CreateModel(
            name="ExpenseParticipant",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("expense", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="participants", to="expenses.expense")),
                ("user_id", models.UUIDField()),
                ("phone_number", models.CharField(max_length=32)),
                ("display_name_snapshot", models.CharField(max_length=255, null=True, blank=True)),
                ("base_share_minor", models.BigIntegerField()),
                ("tax_share_minor", models.BigIntegerField(default=0)),
                ("service_fee_share_minor", models.BigIntegerField(default=0)),
                ("total_share_minor", models.BigIntegerField()),
                ("is_included", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "expense_participants"},
        ),
    ]
