# Generated by Django 5.1.15 on 2026-06-02 21:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("created_by_user_id", models.UUIDField()),
                ("payer_user_id", models.UUIDField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="IRR", max_length=10)),
                ("base_amount_minor", models.BigIntegerField()),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("PERCENTAGE", "PERCENTAGE"),
                            ("FIXED", "FIXED"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("tax_amount_minor", models.BigIntegerField(default=0)),
                (
                    "service_fee_type",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("PERCENTAGE", "PERCENTAGE"),
                            ("FIXED", "FIXED"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "service_fee_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("service_fee_amount_minor", models.BigIntegerField(default=0)),
                ("total_amount_minor", models.BigIntegerField()),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("EQUAL", "EQUAL"),
                            ("CUSTOM_AMOUNT", "CUSTOM_AMOUNT"),
                        ],
                        default="EQUAL",
                        max_length=20,
                    ),
                ),
                ("receipt_file_id", models.UUIDField(blank=True, null=True)),
                (
                    "receipt_url",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("UPDATED", "UPDATED"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "expense_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "expenses_expense",
            },
        ),
        migrations.CreateModel(
            name="GroupProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "EVENT"),
                            ("TRIP", "TRIP"),
                            ("GENERAL", "GENERAL"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("ARCHIVED", "ARCHIVED"),
                            ("DELETED", "DELETED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("member_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "expenses_groupprojection",
            },
        ),
        migrations.CreateModel(
            name="UserProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity_user_id", models.UUIDField(unique=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "USER"), ("ADMIN", "ADMIN")],
                        default="USER",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "expenses_userprojection",
            },
        ),
        migrations.CreateModel(
            name="GroupMemberProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "display_name_snapshot",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "OWNER"),
                            ("ADMIN", "ADMIN"),
                            ("MEMBER", "MEMBER"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("LEFT", "LEFT"),
                            ("REMOVED", "REMOVED"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "expenses_groupmemberprojection",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="expenses_gr_group_i_883698_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="expenses_gr_user_id_270f92_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpenseParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "display_name_snapshot",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("base_share_minor", models.BigIntegerField()),
                ("tax_share_minor", models.BigIntegerField(default=0)),
                ("service_fee_share_minor", models.BigIntegerField(default=0)),
                ("total_share_minor", models.BigIntegerField()),
                ("is_included", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="expenses.expense",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expenseparticipant",
                "unique_together": {("expense", "user_id")},
            },
        ),
    ]
