# Generated by Django 5.1.15 on 2026-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_outboxmessage_inboxmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="expenses_in_event_t_ced93e_idx",
            old_name="expenses_inbox_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="expenses_in_routing_fb934f_idx",
            old_name="expenses_inbox_routing_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="expenses_ou_status_f1377d_idx",
            old_name="expenses_outbox_status_available_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="expenses_ou_routing_e8bd21_idx",
            old_name="expenses_outbox_routing_idx",
        ),
    ]
