# Generated by Django 5.1.15 on 2026-06-23 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_email_art_name_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCardProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_id", models.UUIDField(unique=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("holder_name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("card_number_last4", models.CharField(max_length=4)),
                ("masked_card_number", models.CharField(max_length=24)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "expenses_bankcardprojection",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="expenses_ba_user_id_a4444c_idx",
                    ),
                    models.Index(
                        fields=["user_id", "is_default"],
                        name="expenses_ba_user_id_154803_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpensePaymentOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_card_id", models.UUIDField(db_index=True)),
                ("holder_name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("card_number_last4", models.CharField(max_length=4)),
                ("masked_card_number", models.CharField(max_length=24)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_options",
                        to="expenses.expense",
                    ),
                ),
            ],
            options={
                "db_table": "expenses_expensepaymentoption",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("expense", "bank_card_id"),
                        name="uniq_expense_payment_option",
                    )
                ],
            },
        ),
    ]
