# Generated by Django 5.1.15 on 2026-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_outboxmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="identity_ou_status_ad1dbd_idx",
            old_name="identity_outbox_status_available_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="identity_ou_routing_57f745_idx",
            old_name="identity_outbox_routing_idx",
        ),
    ]
