# Generated by Django 5.1.15 on 2026-06-23 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_user_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBankCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("holder_name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("card_number_last4", models.CharField(max_length=4)),
                ("masked_card_number", models.CharField(max_length=24)),
                ("card_number_hash", models.CharField(max_length=64)),
                ("encrypted_card_number", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_bank_cards",
                "ordering": ["-is_default", "-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_bank_c_user_id_91d68f_idx",
                    ),
                    models.Index(
                        fields=["user", "is_default"],
                        name="user_bank_c_user_id_2bd12c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "card_number_hash"),
                        name="uniq_user_bank_card_hash",
                    )
                ],
            },
        ),
    ]
