# Generated by ChatGPT on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_passwordresetchallenge_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_file_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
