@baseUrl = http://localhost:8080

POST {{baseUrl}}/api/v1/groups/{{groupId}}/expenses/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Lunch",
  "amount": 900000,
  "paid_by": "{{memberId}}",
  "participants": ["{{memberId}}","{{secondMemberId}}","{{thirdMemberId}}"],
  "currency": "IRR"
}

GET {{baseUrl}}/api/v1/groups/{{groupId}}/expenses/list/
Authorization: Bearer {{accessToken}}
