@baseUrl = http://localhost:8080

POST {{baseUrl}}/api/v1/media/receipts/
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

--data
file=@/path/to/receipt.jpg
group_id={{groupId}}

GET {{baseUrl}}/api/v1/media/groups/{{groupId}}/media/
Authorization: Bearer {{accessToken}}
