# Generated by Django 5.1.15 on 2026-06-24 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_user_id', models.UUIDField(db_index=True, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('art_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(default='USER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_user_projections',
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('source_service', models.CharField(max_length=128)),
                ('routing_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_inbox_messages',
                'indexes': [models.Index(fields=['event_type'], name='wallet_inbo_event_t_fb49e0_idx'), models.Index(fields=['routing_key'], name='wallet_inbo_routing_dc0f1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('source_service', models.CharField(default='wallet-service', max_length=128)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('routing_key', models.CharField(max_length=128)),
                ('exchange', models.CharField(default='hamdong.wallet', max_length=128)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('causation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_outbox_messages',
                'indexes': [models.Index(fields=['status', 'available_at'], name='wallet_outb_status_2f4426_idx'), models.Index(fields=['routing_key'], name='wallet_outb_routing_de8c7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettlementItemProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(db_index=True, unique=True)),
                ('plan_id', models.UUIDField(db_index=True)),
                ('group_id', models.UUIDField(db_index=True)),
                ('payer_user_id', models.UUIDField(db_index=True)),
                ('payee_user_id', models.UUIDField(db_index=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('item_status', models.CharField(choices=[('PENDING', 'Pending'), ('REPORTED', 'Reported'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('plan_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('wallet_payment_transaction_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('wallet_payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'wallet_settlement_item_projections',
                'indexes': [models.Index(fields=['payer_user_id', 'plan_status', 'item_status'], name='wallet_sett_payer_u_fb664e_idx'), models.Index(fields=['payee_user_id', 'plan_status', 'item_status'], name='wallet_sett_payee_u_5accd8_idx'), models.Index(fields=['group_id', 'plan_status'], name='wallet_sett_group_i_9d5d9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('available_balance_minor', models.BigIntegerField(default=0)),
                ('reserved_balance_minor', models.BigIntegerField(default=0)),
                ('total_inflow_minor', models.BigIntegerField(default=0)),
                ('total_outflow_minor', models.BigIntegerField(default=0)),
                ('last_ledger_recalculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_wallets',
                'indexes': [models.Index(fields=['user_id', 'status'], name='wallet_wall_user_id_163b11_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'currency'), name='wallet_unique_user_currency')],
            },
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('provider', models.CharField(default='FAKE', max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_topups',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received'), ('SETTLEMENT_PAYMENT', 'Settlement Payment'), ('SETTLEMENT_RECEIVED', 'Settlement Received'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=64, null=True)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('AVAILABLE_DEBIT', 'Available Debit'), ('AVAILABLE_CREDIT', 'Available Credit'), ('RESERVED_DEBIT', 'Reserved Debit'), ('RESERVED_CREDIT', 'Reserved Credit')], max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallet')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallets.wallettransaction')),
            ],
            options={
                'db_table': 'wallet_ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('payment_method_id', models.UUIDField()),
                ('payment_method_masked', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_cancel_record', to='wallets.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet')),
                ('withdrawal_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_record', to='wallets.wallettransaction')),
            ],
            options={
                'db_table': 'wallet_withdrawals',
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'status'], name='wallet_tran_wallet__7ce472_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'type', 'status'], name='wallet_tran_wallet__1dc269_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'direction', 'created_at'], name='wallet_tran_wallet__54e199_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallet_tran_referen_f20c6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='wallet_tx_unique_wallet_idempotency'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'entry_type'], name='wallet_ledg_wallet__c9a5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction'], name='wallet_ledg_transac_cbf5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['wallet', 'status'], name='wallet_with_wallet__17d5bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='wallet_withdrawal_unique_wallet_idempotency'),
        ),
    ]
