# Generated by Django 5.1.15 on 2026-06-24 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FAKE', 'Fake Provider')], default='FAKE', max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('CALLBACK_RECEIVED', 'Callback Received'), ('VERIFYING', 'Verifying'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('RETRYABLE', 'Retryable')], default='CALLBACK_RECEIVED', max_length=32)),
                ('callback_count', models.PositiveIntegerField(default=0)),
                ('provider_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('provider_currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('provider_status', models.CharField(blank=True, max_length=64, null=True)),
                ('last_callback_payload', models.JSONField(blank=True, default=dict)),
                ('last_verify_response', models.JSONField(blank=True, default=dict)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_gateway_transactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FAKE', 'Fake Provider')], default='FAKE', max_length=32)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('method', models.CharField(max_length=8)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wallet_payment_callback_logs',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('WALLET_TOP_UP', 'Wallet Top Up'), ('SETTLEMENT_PAYMENT', 'Settlement Payment')], default='WALLET_TOP_UP', max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('provider', models.CharField(choices=[('FAKE', 'Fake Provider')], default='FAKE', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('REDIRECT_REQUIRED', 'Redirect Required'), ('CALLBACK_RECEIVED', 'Callback Received'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('RETRYABLE', 'Retryable'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='REDIRECT_REQUIRED', max_length=32)),
                ('payment_url', models.URLField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_payment_intents',
            },
        ),
        migrations.AddField(
            model_name='topup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_up_record', to='wallets.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='provider',
            field=models.CharField(choices=[('FAKE', 'Fake Provider')], default='FAKE', max_length=64),
        ),
        migrations.AddIndex(
            model_name='outboxmessage',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='wallet_outb_aggrega_daa144_idx'),
        ),
        migrations.AddField(
            model_name='topup',
            name='gateway_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_up', to='wallets.gatewaytransaction'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='paymentcallbacklog',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_logs', to='wallets.paymentintent'),
        ),
        migrations.AddField(
            model_name='gatewaytransaction',
            name='payment_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transaction', to='wallets.paymentintent'),
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_up', to='wallets.paymentintent'),
        ),
        migrations.AddIndex(
            model_name='topup',
            index=models.Index(fields=['wallet', 'status'], name='wallet_topu_wallet__48b016_idx'),
        ),
        migrations.AddConstraint(
            model_name='topup',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='wallet_topup_unique_wallet_idempotency'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['wallet', 'status'], name='wallet_paym_wallet__2b499f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'status'], name='wallet_paym_provide_d566d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['expires_at'], name='wallet_paym_expires_28068f_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('wallet', 'idempotency_key'), name='wallet_payment_intent_unique_wallet_idempotency'),
        ),
        migrations.AddIndex(
            model_name='paymentcallbacklog',
            index=models.Index(fields=['provider', 'provider_reference'], name='wallet_paym_provide_161ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallbacklog',
            index=models.Index(fields=['payment_intent', 'received_at'], name='wallet_paym_payment_bc68e1_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['provider', 'status'], name='wallet_gate_provide_57cb01_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewaytransaction',
            index=models.Index(fields=['provider', 'provider_reference'], name='wallet_gate_provide_0136a3_idx'),
        ),
    ]
