# Generated by Django 5.1.15 on 2026-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallets",
            "0002_gatewaytransaction_paymentcallbacklog_paymentintent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatewaytransaction",
            name="provider",
            field=models.CharField(
                choices=[("FAKE", "Fake Provider"), ("ZARINPAL", "Zarinpal")],
                default="FAKE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="paymentcallbacklog",
            name="provider",
            field=models.CharField(
                choices=[("FAKE", "Fake Provider"), ("ZARINPAL", "Zarinpal")],
                default="FAKE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="provider",
            field=models.CharField(
                choices=[("FAKE", "Fake Provider"), ("ZARINPAL", "Zarinpal")],
                default="FAKE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="topup",
            name="provider",
            field=models.CharField(
                choices=[("FAKE", "Fake Provider"), ("ZARINPAL", "Zarinpal")],
                default="FAKE",
                max_length=64,
            ),
        ),
    ]
