# Generated by Django 5.1.15 on 2026-05-30 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("EMAIL", "Email"), ("PUSH", "Push")],
                        max_length=16,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("OTP", "OTP"),
                            ("REMINDER", "Reminder"),
                            ("INVITE", "Invite"),
                            ("SETTLEMENT", "Settlement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recipient", models.CharField(max_length=32)),
                ("recipient_masked", models.CharField(max_length=32)),
                (
                    "template_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("RETRY_PENDING", "Retry pending"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("fake", "Fake"),
                            ("kavenegar", "Kavenegar"),
                            ("melipayamak", "Melipayamak"),
                        ],
                        default="fake",
                        max_length=32,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_sms_templates",
            },
        ),
        migrations.CreateModel(
            name="ProviderDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("fake", "Fake"),
                            ("kavenegar", "Kavenegar"),
                            ("melipayamak", "Melipayamak"),
                        ],
                        default="fake",
                        max_length=32,
                    ),
                ),
                ("request_payload_masked", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notifications.notificationmessage",
                    ),
                ),
            ],
            options={
                "db_table": "provider_delivery_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
