# Generated by Django 5.2.4 on 2026-06-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationjob"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notification_event_i_064516_idx",
            old_name="notification_event_2a7a73_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notification_status_0b82f0_idx",
            old_name="notification_status_7ac2f5_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notification_recipie_fa20c0_idx",
            old_name="notification_recipient_0f1c4b_idx",
        ),
    ]