# Generated by Django 5.2.4 on 2026-06-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_rename_notification_event_2a7a73_idx_notification_event_i_064516_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notificatio_event_i_064516_idx",
            old_name="notification_event_i_064516_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notificatio_status_0b82f0_idx",
            old_name="notification_status_0b82f0_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationjob",
            new_name="notificatio_recipie_fa20c0_idx",
            old_name="notification_recipie_fa20c0_idx",
        ),
    ]