# Generated by Django 5.1.15 on 2026-06-04 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_phase9_outbox_inbox_and_job_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="notificatio_event_t_837d3d_idx",
            old_name="notifications_inbox_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="notificatio_routing_7025be_idx",
            old_name="notifications_inbox_routing_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="notificatio_status_57b11a_idx",
            old_name="notifications_outbox_status_available_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="notificatio_routing_dc1851_idx",
            old_name="notifications_outbox_routing_idx",
        ),
        migrations.AlterField(
            model_name="notificationjob",
            name="scheduled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notificationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENDING", "Sending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="scheduled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
