# Generated by Django 5.1.15 on 2026-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notification_message_body_crud_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationjob",
            name="channel",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("PUSH", "Push"),
                    ("IN_APP", "In app"),
                ],
                default="SMS",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="channel",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("PUSH", "Push"),
                    ("IN_APP", "In app"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("OTP", "OTP"),
                    ("REMINDER", "Reminder"),
                    ("INVITE", "Invite"),
                    ("SETTLEMENT", "Settlement"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="recipient_phone_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("SENDING", "Sending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("RETRY_PENDING", "Retry pending"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
