# Generated by Django 5.1.15 on 2026-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notificationjob_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmessage",
            name="provider",
            field=models.CharField(
                choices=[
                    ("fake", "Fake"),
                    ("kavenegar", "Kavenegar"),
                    ("melipayamak", "Melipayamak"),
                    ("smsir", "SMS.ir"),
                ],
                default="fake",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerdeliverylog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("fake", "Fake"),
                    ("kavenegar", "Kavenegar"),
                    ("melipayamak", "Melipayamak"),
                    ("smsir", "SMS.ir"),
                ],
                default="fake",
                max_length=32,
            ),
        ),
    ]
