# Generated by Django 5.1.15 on 2026-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_email_delivery_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationjob",
            name="channel",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("PUSH", "Push"), ("IN_APP", "In app")],
                default="EMAIL",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="notificationjob",
            name="recipient",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="notificationjob",
            name="recipient_masked",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="channel",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("PUSH", "Push"), ("IN_APP", "In app")],
                default="EMAIL",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="provider",
            field=models.CharField(
                choices=[("fake", "Fake"), ("smtp", "SMTP")],
                default="fake",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="recipient",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="notificationmessage",
            name="recipient_masked",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="providerdeliverylog",
            name="provider",
            field=models.CharField(
                choices=[("fake", "Fake"), ("smtp", "SMTP")],
                default="fake",
                max_length=32,
            ),
        ),
    ]
