# Generated by Django 5.1.15 on 2026-06-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_alter_notificationjob_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENDING", "Sending"),
                    ("PARTIALLY_SENT", "Partially sent"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
