# Generated by Django 5.1.15 on 2026-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_alter_notificationjob_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationmessage",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notificationmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="notificationmessage",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_read=False, read_at__isnull=True)
                    | models.Q(is_read=True, read_at__isnull=False)
                ),
                name="notif_read_state_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(fields=["recipient_user_id", "created_at"], name="notif_recipient_created_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(fields=["recipient_user_id", "is_read"], name="notif_recipient_read_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(fields=["recipient_user_id", "priority", "is_read"], name="notif_recipient_priority_read_idx"),
        ),
    ]
