# Generated by Django 5.1.15 on 2026-06-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_notificationmessage_read_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationmessage",
            options={"db_table": "notification_messages", "ordering": ["-created_at", "-id"]},
        ),
    ]
