# Generated by Django 5.1.15 on 2026-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_outboxmessage_inboxmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="groups_inbo_event_t_b211cc_idx",
            old_name="groups_inbox_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="groups_inbo_routing_fd9efc_idx",
            old_name="groups_inbox_routing_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="groups_outb_status_c0225b_idx",
            old_name="groups_outbox_status_available_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="groups_outb_routing_49bda8_idx",
            old_name="groups_outbox_routing_idx",
        ),
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[("EVENT", "Event"), ("TRIP", "Trip"), ("GENERAL", "General")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("USED", "Used"),
                    ("REVOKED", "Revoked"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("MEMBER", "Member")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LEFT", "Left"),
                    ("REMOVED", "Removed"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
