# Generated by Django 5.1.15 on 2026-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_email_art_name_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invite_type',
            field=models.CharField(choices=[('TOKEN', 'Token'), ('DIRECT', 'Direct')], default='TOKEN', max_length=16),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='recipient_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='recipient_user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='groupinvite',
            index=models.Index(fields=['group', 'invite_type', 'status'], name='group_invite_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvite',
            index=models.Index(fields=['recipient_user_id', 'invite_type', 'status'], name='group_invite_recipient_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupinvite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invite_type', 'TOKEN'), ('token_hash__isnull', False)), models.Q(('invite_type', 'DIRECT'), ('recipient_user_id__isnull', False)), _connector='OR'), name='group_invite_type_required_fields'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user_id'), name='group_member_unique_group_user'),
        ),
    ]
