# Generated by Django 5.1.15 on 2026-05-31 08:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expense_id", models.UUIDField(db_index=True, unique=True)),
                ("group_id", models.UUIDField(db_index=True)),
                ("created_by_user_id", models.UUIDField()),
                ("payer_user_id", models.UUIDField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                ("base_amount_minor", models.BigIntegerField(default=0)),
                ("tax_amount_minor", models.BigIntegerField(default=0)),
                ("service_fee_amount_minor", models.BigIntegerField(default=0)),
                ("total_amount_minor", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UPDATED", "Updated"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("expense_version", models.PositiveIntegerField(default=1)),
                (
                    "expense_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_expense_projections",
            },
        ),
        migrations.CreateModel(
            name="GroupProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event"),
                            ("TRIP", "Trip"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_group_projections",
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True, unique=True)),
                ("event_type", models.CharField(max_length=128)),
                ("source_service", models.CharField(max_length=128)),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "settlement_processed_events",
            },
        ),
        migrations.CreateModel(
            name="UserProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity_user_id", models.UUIDField(db_index=True, unique=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "User"), ("ADMIN", "Admin")],
                        default="USER",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_user_projections",
            },
        ),
        migrations.CreateModel(
            name="DebtLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                (
                    "source_expense_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("source_expense_version", models.PositiveIntegerField(default=1)),
                ("debtor_user_id", models.UUIDField(db_index=True)),
                ("creditor_user_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.BigIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE_SHARE", "Expense Share"),
                            ("EXPENSE_REVERSAL", "Expense Reversal"),
                            ("MANUAL_SETTLEMENT", "Manual Settlement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REVERSED", "Reversed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_debt_ledger_entries",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_a5c9d0_idx"
                    ),
                    models.Index(
                        fields=["source_expense_id"],
                        name="settlement__source__6fee37_idx",
                    ),
                    models.Index(
                        fields=["debtor_user_id"], name="settlement__debtor__173c64_idx"
                    ),
                    models.Index(
                        fields=["creditor_user_id"],
                        name="settlement__credito_885d57_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpenseParticipantProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expense_id", models.UUIDField(db_index=True)),
                ("group_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("base_share_minor", models.BigIntegerField(default=0)),
                ("tax_share_minor", models.BigIntegerField(default=0)),
                ("service_fee_share_minor", models.BigIntegerField(default=0)),
                ("total_share_minor", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_expense_participant_projections",
                "indexes": [
                    models.Index(
                        fields=["expense_id"], name="settlement__expense_b1fee7_idx"
                    ),
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_d17736_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="settlement__user_id_cf2f90_idx"
                    ),
                ],
                "unique_together": {("expense_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="GroupBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                ("total_paid_minor", models.BigIntegerField(default=0)),
                ("total_share_minor", models.BigIntegerField(default=0)),
                ("total_settled_paid_minor", models.BigIntegerField(default=0)),
                ("total_settled_received_minor", models.BigIntegerField(default=0)),
                ("net_balance_minor", models.BigIntegerField(default=0)),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_group_balance_snapshots",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_c6d228_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="settlement__user_id_692850_idx"
                    ),
                ],
                "unique_together": {("group_id", "user_id", "currency")},
            },
        ),
        migrations.CreateModel(
            name="GroupMemberProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "display_name_snapshot",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LEFT", "Left"),
                            ("REMOVED", "Removed"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_group_member_projections",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_4fb0df_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="settlement__user_id_91351d_idx"
                    ),
                ],
                "unique_together": {("group_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="ManualSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                ("payer_user_id", models.UUIDField(db_index=True)),
                ("receiver_user_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.BigIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_CONFIRMATION",
                        max_length=30,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("confirmed_by_user_id", models.UUIDField(blank=True, null=True)),
                ("rejected_by_user_id", models.UUIDField(blank=True, null=True)),
                ("cancelled_by_user_id", models.UUIDField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_manual_settlements",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_fed0fc_idx"
                    ),
                    models.Index(
                        fields=["payer_user_id"], name="settlement__payer_u_65f3e3_idx"
                    ),
                    models.Index(
                        fields=["receiver_user_id"],
                        name="settlement__receive_7e47f8_idx",
                    ),
                ],
            },
        ),
    ]
