# Generated by Django 5.1.15 on 2026-05-31 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("generated_by_user_id", models.UUIDField()),
                ("activated_by_user_id", models.UUIDField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("source_balance_calculated_at", models.DateTimeField()),
                ("total_debt_minor", models.BigIntegerField(default=0)),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_settlement_plans",
                "indexes": [
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_762ddb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="settlement__status_2c14ef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettlementPlanEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settlement_plan_id", models.UUIDField(db_index=True)),
                (
                    "settlement_plan_item_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("actor_user_id", models.UUIDField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PLAN_GENERATED", "Plan Generated"),
                            ("PLAN_ACTIVATED", "Plan Activated"),
                            ("PLAN_CANCELLED", "Plan Cancelled"),
                            ("PLAN_EXPIRED", "Plan Expired"),
                            ("ITEM_REPORTED", "Item Reported"),
                            ("ITEM_CONFIRMED", "Item Confirmed"),
                            ("ITEM_REJECTED", "Item Rejected"),
                            ("ITEM_CANCELLED", "Item Cancelled"),
                            ("PLAN_COMPLETED", "Plan Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "settlement_settlement_plan_event_logs",
                "indexes": [
                    models.Index(
                        fields=["settlement_plan_id"],
                        name="settlement__settlem_f062cc_idx",
                    ),
                    models.Index(
                        fields=["settlement_plan_item_id"],
                        name="settlement__settlem_300d9d_idx",
                    ),
                    models.Index(
                        fields=["actor_user_id"], name="settlement__actor_u_818400_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="settlement__event_t_623e65_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettlementPlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("settlement_plan_id", models.UUIDField(db_index=True)),
                ("group_id", models.UUIDField(db_index=True)),
                ("payer_user_id", models.UUIDField(db_index=True)),
                ("receiver_user_id", models.UUIDField(db_index=True)),
                ("amount_minor", models.BigIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Iranian Rial")], default="IRR", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REPORTED", "Reported"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("manual_settlement_id", models.UUIDField(blank=True, null=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_settlement_plan_items",
                "indexes": [
                    models.Index(
                        fields=["settlement_plan_id"],
                        name="settlement__settlem_fa6451_idx",
                    ),
                    models.Index(
                        fields=["group_id"], name="settlement__group_i_8b134b_idx"
                    ),
                    models.Index(
                        fields=["payer_user_id"], name="settlement__payer_u_0d714f_idx"
                    ),
                    models.Index(
                        fields=["receiver_user_id"],
                        name="settlement__receive_09b72a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="settlement__status_7a5caf_idx"
                    ),
                ],
            },
        ),
    ]
