# Generated by Django 5.2.4 on 2026-06-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0003_outboxmessage_reminderdispatchlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="settlement__status_142d3a_idx",
            old_name="settlement_o_status_a7a0f7_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="settlement__routing_832be7_idx",
            old_name="settlement_o_routing_ef5c23_idx",
        ),
        migrations.RenameIndex(
            model_name="outboxmessage",
            new_name="settlement__aggrega_9731de_idx",
            old_name="settlement_o_aggregate_7e9c7d_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderdispatchlog",
            new_name="settlement__reminde_376581_idx",
            old_name="settlement_r_reminder_2d3d54_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderdispatchlog",
            new_name="settlement__recipie_bf13cf_idx",
            old_name="settlement_r_recipie_d98f60_idx",
        ),
        migrations.RenameIndex(
            model_name="reminderdispatchlog",
            new_name="settlement__next_al_52f64c_idx",
            old_name="settlement_r_next_al_ee1ce1_idx",
        ),
    ]