# Generated by Django 5.1.15 on 2026-06-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0005_inboxmessage_outbox_event_version"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="settlement__event_t_60e3f1_idx",
            old_name="settlement_inbox_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="inboxmessage",
            new_name="settlement__routing_ce4882_idx",
            old_name="settlement_inbox_routing_idx",
        ),
        migrations.AlterField(
            model_name="outboxmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PUBLISHED", "Published"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
