# Generated by Django 5.1.15 on 2026-06-21 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0008_automatic_debt_reminders"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="debtreminderrequest",
            new_name="settlement__group_i_b3a22b_idx",
            old_name="settlement__group_i_5af738_idx",
        ),
        migrations.RenameIndex(
            model_name="debtreminderrequest",
            new_name="settlement__settlem_be6122_idx",
            old_name="settlement__settlem_a2f212_idx",
        ),
        migrations.RenameIndex(
            model_name="debtreminderrequest",
            new_name="settlement__recipie_733e53_idx",
            old_name="settlement__recipi_507541_idx",
        ),
        migrations.RenameIndex(
            model_name="debtreminderrequest",
            new_name="settlement__status_f6ca3d_idx",
            old_name="settlement__status_f92644_idx",
        ),
        migrations.RenameIndex(
            model_name="debtreminderrequest",
            new_name="settlement__source_2c3d70_idx",
            old_name="settlement__source_77dbab_idx",
        ),
        migrations.RenameIndex(
            model_name="groupremindersettings",
            new_name="settlement__group_i_98c874_idx",
            old_name="settlement__group_i_e722d2_idx",
        ),
        migrations.AlterField(
            model_name="debtreminderrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="debtreminderrequest",
            name="scheduled_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddIndex(
            model_name="debtreminderrequest",
            index=models.Index(
                fields=["dedupe_key"], name="settlement__dedupe__5351b9_idx"
            ),
        ),
    ]
