# Generated by Django 5.1.15 on 2026-06-23 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settlements",
            "0009_rename_settlement__group_i_5af738_idx_settlement__group_i_b3a22b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manualsettlement",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_to_bank_card_bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_to_bank_card_holder_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_to_bank_card_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_to_bank_card_last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="paid_to_bank_card_masked_number",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="payment_method",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="receipt_file_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualsettlement",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="BankCardProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_id", models.UUIDField(unique=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("holder_name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("card_number_last4", models.CharField(max_length=4)),
                ("masked_card_number", models.CharField(max_length=24)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settlement_bankcardprojection",
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="settlement__user_id_24479a_idx",
                    ),
                    models.Index(
                        fields=["user_id", "is_default"],
                        name="settlement__user_id_111c03_idx",
                    ),
                ],
            },
        ),
    ]
